name: .NET 4.8 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 4.8
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install NuGet
      run: choco install nuget.commandline

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build solution
      run: msbuild your-solution.sln /p:Configuration=Release

    - name: Run tests
      run: |
        vstest.console.exe **\*.Tests.dll
      continue-on-error: true
